name: CI

on: 
    pull_request:
        branches:
            - main

jobs:
    unit-test:
        runs-on: [ubuntu-latest]
        defaults:
            run: 
                working-directory: .

        strategy: 
            matrix: 
                python-version: ['3.10']

        steps:
            - uses: actions/checkout@v3

            - name: Set Up Python
              uses: actions/setup-python@v4
              with: 
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Test Code
              run: python -m pytest -s -v ./tests/
    
    pipeline-test:
        needs: [unit-test]
        runs-on: [ubuntu-latest]
        defaults:
            run: 
                working-directory: .

        strategy: 
            matrix: 
                python-version: ['3.10']

        steps:
            - uses: actions/checkout@v3

            - name: Set Up Python
              uses: actions/setup-python@v4
              with: 
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Test Code
              run: |
                mlflow experiments create -n pipeline_test
                mlflow run --experiment-name pipeline_test . --env-manager=local